Update lint-and-test.yml
flake8 was installed in the test job, but the flake8 command was being run in the lint job. Fixed.

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -1,5 +1,4 @@
 name: Lint and Test
-
 on:
   push:
     branches:
@@ -24,49 +23,16 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
-
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.12'
-
     - name: Install Poetry
       uses: snok/install-poetry@v1
       with:
         version: latest
         virtualenvs-create: true
         virtualenvs-in-project: true
-
-    - name: Install dependencies
-      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
-      run: poetry install --no-interaction --no-root
-
-    - name: Run pre-commit
-      continue-on-error: true
-      run: poetry run pre-commit run --all-files
-
-    - name: Run flake8
-      run: poetry run flake8 app tests
-
-  test:
-    runs-on: ubuntu-latest
-    needs: lint
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.12'
-
-    - name: Install Poetry
-      uses: snok/install-poetry@v1
-      with:
-        version: latest
-        virtualenvs-create: true
-        virtualenvs-in-project: true
-
     - name: Install dependencies
       run: |
         poetry install --no-interaction --no-root
@@ -80,6 +46,36 @@ jobs:
           echo "Failed to add flake8. Attempting to update lock file and retry..."
           poetry lock --no-update
           poetry add flake8 --dev
+        fi
+    - name: Run pre-commit
+      continue-on-error: true
+      run: poetry run pre-commit run --all-files
+    - name: Run flake8
+      run: poetry run flake8 app tests
+
+  test:
+    runs-on: ubuntu-latest
+    needs: lint
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+    - name: Set up Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.12'
+    - name: Install Poetry
+      uses: snok/install-poetry@v1
+      with:
+        version: latest
+        virtualenvs-create: true
+        virtualenvs-in-project: true
+    - name: Install dependencies
+      run: |
+        poetry install --no-interaction --no-root
+        if [ $? -ne 0 ]; then
+          echo "Poetry install failed. Attempting to update lock file and retry..."
+          poetry lock --no-update
+          poetry install --no-interaction --no-root
         fi
     - name: Run tests
       run: poetry run pytest tests
